"""
GridForge V2 Protection System
==============================

File:
    core/protection/protection_system.py

Purpose
-------
Provides system-level orchestration of GridForge V2
ProtectionElement objects.

Architectural position
----------------------

    Physical Relay
          |
          +-- ProtectionElement
          |       |
          |       +-- RelayBase
          |
          +-- ProtectionElement
          |       |
          |       +-- RelayBase
          |
          +-- ProtectionElement
                  |
                  +-- RelayBase

                         |
                         v

                 ProtectionSystem
                         |
                         v
                ProtectionDecision
                         |
                         v
              Protection Output Layer
                         |
                         v
                  BreakerManager

ProtectionSystem is an orchestration layer.

It does NOT:

    - own physical Relay objects;
    - create measurement channels;
    - create RelayInput objects;
    - calculate electrical quantities;
    - perform load flow;
    - perform short-circuit analysis;
    - perform relay coordination;
    - operate breakers;
    - schedule breaker operations.

Multifunction relay architecture
--------------------------------

GridForge V2 deliberately supports:

    one Relay
        |
        +-- zero or more ProtectionElements

Therefore a single physical relay may host:

    50/51
    67
    21
    27
    59
    81
    87
    50BF
    ...

Each ProtectionElement owns the composition identity of one
protection function while the authoritative physical Relay remains
in the model layer.

Execution architecture
----------------------

    MeasurementChannel
            |
            v
       RelayInput
            |
            v
      ProtectionContext
            |
            v
      RelayBase.evaluate()
            |
            v
    ProtectionDecision
            |
            v
     ProtectionElement
            |
            v
     ProtectionSystem
            |
            v
 Protection output / scheme
            |
            v
      BreakerManager

Decision ownership
------------------

ProtectionSystem collects complete ProtectionDecision objects.

It does NOT reduce decisions to booleans or construct breaker
commands.

A ProtectionDecision contains the semantic protection result:

    pickup
    operate
    trip_request
    blocked
    valid
    operating information
    diagnostics

Physical breaker operation belongs to BreakerManager.

Execution context
-----------------

ProtectionSystem accepts an optional ProtectionContext.

The context belongs to the protection execution environment and
provides time/state information required by protection functions.

ProtectionSystem does not interpret electrical quantities contained
in the context.

Decision lifecycle
------------------

The latest evaluation results are retained internally so that:

    - operated_elements()
    - tripped_elements()
    - latest_decisions()
    - status()

can operate on the actual ProtectionDecision results generated by
the latest evaluation cycle.

Copyright © 2026 Subhendu Mishra
All Rights Reserved.
Proprietary and confidential.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Mapping

from .context import ProtectionContext
from .decision import ProtectionDecision
from .protection_element import ProtectionElement


class ProtectionSystem:
    """
    GridForge V2 protection-system orchestration service.

    ProtectionSystem owns the runtime registry of ProtectionElement
    objects.

    The authoritative physical Relay remains the Relay model in
    ``core.model.relay``.
    """

    # =================================================================
    # INITIALIZATION
    # =================================================================

    def __init__(self) -> None:
        """
        Initialize an empty protection-system registry.
        """

        self._elements: Dict[Any, ProtectionElement] = {}

        # Decisions produced by the most recent evaluation cycle.

        self._last_decisions: tuple[
            ProtectionDecision,
            ...
        ] = ()

    # =================================================================
    # ELEMENT REGISTRATION
    # =================================================================

    def add_element(
        self,
        element: ProtectionElement,
    ) -> None:
        """
        Register a protection element.

        Parameters
        ----------
        element:
            ProtectionElement to register.

        Raises
        ------
        TypeError
            If the supplied object is not a ProtectionElement.

        ValueError
            If the element identifier is already registered.
        """

        if not isinstance(
            element,
            ProtectionElement,
        ):
            raise TypeError(
                "element must be a ProtectionElement."
            )

        if element.id in self._elements:
            raise ValueError(
                f"Protection element '{element.id}' "
                "is already registered."
            )

        self._elements[element.id] = element

    # -----------------------------------------------------------------

    def remove_element(
        self,
        element_id: Any,
    ) -> ProtectionElement:
        """
        Remove and return a registered protection element.
        """

        try:
            element = self._elements.pop(
                element_id
            )
        except KeyError as exc:
            raise KeyError(
                f"Protection element '{element_id}' "
                "is not registered."
            ) from exc

        # The removed element may have contributed to the previous
        # decision cycle. Clear the cached decision because the
        # registry has changed.

        self._last_decisions = ()

        return element

    # -----------------------------------------------------------------

    def has_element(
        self,
        element_id: Any,
    ) -> bool:
        """
        Return True when an element is registered.
        """

        return element_id in self._elements

    # -----------------------------------------------------------------

    def get_element(
        self,
        element_id: Any,
    ) -> ProtectionElement:
        """
        Return a registered protection element.
        """

        try:
            return self._elements[
                element_id
            ]
        except KeyError as exc:
            raise KeyError(
                f"Protection element '{element_id}' "
                "is not registered."
            ) from exc

    # =================================================================
    # COLLECTION ACCESS
    # =================================================================

    @property
    def elements(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return all registered protection elements.

        A tuple prevents callers from modifying the internal
        registry directly.
        """

        return tuple(
            self._elements.values()
        )

    # -----------------------------------------------------------------

    def iter_elements(
        self,
    ) -> Iterable[ProtectionElement]:
        """
        Iterate over registered protection elements.

        Iteration follows registration order.

        Evaluation order is controlled separately by
        ``_execution_order()``.
        """

        return iter(
            self._elements.values()
        )

    # =================================================================
    # RELAY COMPOSITION
    # =================================================================

    def elements_for_relay(
        self,
        relay_id: Any,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return all protection elements hosted by a Relay.

        This is the primary multifunction-relay access pattern.
        """

        return tuple(
            element
            for element in self._elements.values()
            if element.relay_id == relay_id
        )

    # -----------------------------------------------------------------

    def relays(
        self,
    ) -> tuple[Any, ...]:
        """
        Return unique authoritative Relay objects represented by the
        registered protection elements.

        Relay identity and Relay state remain owned by the Relay
        model.
        """

        result: List[Any] = []

        seen: set[int] = set()

        for element in self._elements.values():

            relay = element.relay_model

            identity = id(
                relay
            )

            if identity in seen:
                continue

            seen.add(
                identity
            )

            result.append(
                relay
            )

        return tuple(
            result
        )

    # =================================================================
    # FUNCTION TYPE ACCESS
    # =================================================================

    def elements_by_type(
        self,
        function_type: str,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements of a specified function type.

        Examples
        --------

            OVERCURRENT
            DIRECTIONAL
            DISTANCE
            DIFFERENTIAL
            VOLTAGE
            FREQUENCY
            POWER
            BREAKER_FAILURE
        """

        if not isinstance(
            function_type,
            str,
        ):
            raise TypeError(
                "function_type must be a string."
            )

        normalized = (
            function_type.strip().upper()
        )

        if not normalized:
            raise ValueError(
                "function_type cannot be empty."
            )

        return tuple(
            element
            for element in self._elements.values()
            if element.function_type
            == normalized
        )

    # =================================================================
    # EXECUTION ORDER
    # =================================================================

    def _execution_order(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements in deterministic execution order.

        Ordering rules
        --------------

        1. Lower priority values execute first.
        2. Element identifier provides deterministic tie-breaking.

        Priority is an orchestration ordering mechanism.

        It is NOT interpreted as:

            - relay coordination time;
            - TMS;
            - grading margin;
            - electrical selectivity.

        Those belong to the coordination layer.
        """

        return tuple(
            sorted(
                self._elements.values(),
                key=lambda element: (
                    element.priority,
                    str(element.id),
                ),
            )
        )

    # =================================================================
    # EVALUATION
    # =================================================================

    def evaluate(
        self,
        context: ProtectionContext | None = None,
    ) -> tuple[ProtectionDecision, ...]:
        """
        Evaluate all enabled protection elements.

        Parameters
        ----------
        context:
            Optional ProtectionContext supplied to the protection
            execution layer.

        Returns
        -------
        tuple[ProtectionDecision, ...]
            Complete decisions produced during this evaluation cycle.

        Notes
        -----
        ProtectionSystem performs orchestration only.

        It does not:

            - calculate fault current;
            - determine network electrical quantities;
            - coordinate relays;
            - issue breaker commands;
            - schedule delayed trips.

        Each ProtectionElement is responsible for invoking its
        associated protection-function implementation.

        The resulting ProtectionDecision is retained as the latest
        decision for that element.
        """

        decisions: List[
            ProtectionDecision
        ] = []

        for element in self._execution_order():

            if not element.enabled:
                continue

            decision = element.evaluate(
                context
            )

            if not isinstance(
                decision,
                ProtectionDecision,
            ):
                raise TypeError(
                    f"Protection element '{element.id}' "
                    "returned an invalid evaluation result. "
                    "Expected ProtectionDecision."
                )

            decisions.append(
                decision
            )

        self._last_decisions = tuple(
            decisions
        )

        return self._last_decisions

    # =================================================================
    # LATEST DECISIONS
    # =================================================================

    @property
    def last_decisions(
        self,
    ) -> tuple[ProtectionDecision, ...]:
        """
        Return the decisions produced by the most recent evaluation
        cycle.

        An immutable tuple is returned so callers cannot modify the
        system's decision collection.
        """

        return self._last_decisions

    # -----------------------------------------------------------------

    def latest_decisions(
        self,
    ) -> tuple[ProtectionDecision, ...]:
        """
        Return the decisions from the most recent evaluation cycle.

        This method is provided as an explicit API counterpart to the
        ``last_decisions`` property.
        """

        return self._last_decisions

    # =================================================================
    # DECISION LOOKUP
    # =================================================================

    def decision_for_element(
        self,
        element_id: Any,
    ) -> ProtectionDecision | None:
        """
        Return the latest decision for a specific protection element.

        Returns None when the element has not participated in the most
        recent evaluation cycle.
        """

        for decision in self._last_decisions:

            if decision.element_id == element_id:
                return decision

        return None

    # -----------------------------------------------------------------

    def decisions_for_relay(
        self,
        relay_id: Any,
    ) -> tuple[ProtectionDecision, ...]:
        """
        Return latest decisions associated with a Relay.
        """

        return tuple(
            decision
            for decision in self._last_decisions
            if decision.relay_id == relay_id
        )

    # -----------------------------------------------------------------

    def decisions_by_function_type(
        self,
        function_type: str,
    ) -> tuple[ProtectionDecision, ...]:
        """
        Return latest decisions belonging to a function type.

        The function type is obtained from the corresponding
        ProtectionElement rather than being duplicated into the
        ProtectionDecision contract.
        """

        if not isinstance(
            function_type,
            str,
        ):
            raise TypeError(
                "function_type must be a string."
            )

        normalized = (
            function_type.strip().upper()
        )

        if not normalized:
            raise ValueError(
                "function_type cannot be empty."
            )

        element_ids = {
            element.id
            for element in self.elements_by_type(
                normalized
            )
        }

        return tuple(
            decision
            for decision in self._last_decisions
            if decision.element_id
            in element_ids
        )

    # =================================================================
    # DECISION QUERIES
    # =================================================================

    def operated_elements(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements whose latest decision reports
        ``operate=True``.

        No protection-function implementation internals are inspected.
        """

        operated_ids = {
            decision.element_id
            for decision in self._last_decisions
            if (
                decision.valid
                and not decision.blocked
                and decision.operate
            )
        }

        return tuple(
            element
            for element in self._elements.values()
            if element.id in operated_ids
        )

    # -----------------------------------------------------------------

    def tripped_elements(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements whose latest decision requests a
        trip.

        A trip request is a protection decision.

        It is NOT physical breaker operation.
        """

        trip_ids = {
            decision.element_id
            for decision in self._last_decisions
            if decision.actionable
        }

        return tuple(
            element
            for element in self._elements.values()
            if element.id in trip_ids
        )

    # -----------------------------------------------------------------

    def pickup_elements(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements whose latest decision reports
        pickup.
        """

        pickup_ids = {
            decision.element_id
            for decision in self._last_decisions
            if (
                decision.valid
                and decision.pickup
            )
        }

        return tuple(
            element
            for element in self._elements.values()
            if element.id in pickup_ids
        )

    # -----------------------------------------------------------------

    def blocked_elements(
        self,
    ) -> tuple[ProtectionElement, ...]:
        """
        Return protection elements whose latest decision reports
        blocking.
        """

        blocked_ids = {
            decision.element_id
            for decision in self._last_decisions
            if decision.blocked
        }

        return tuple(
            element
            for element in self._elements.values()
            if element.id in blocked_ids
        )

    # =================================================================
    # RESET
    # =================================================================

    def reset(
        self,
    ) -> None:
        """
        Reset all registered protection elements and clear the latest
        decision cycle.
        """

        for element in self._elements.values():
            element.reset()

        self._last_decisions = ()

    # =================================================================
    # COMPATIBILITY VIEWS
    # =================================================================

    @property
    def oc_relays(
        self,
    ) -> List[Any]:
        """
        Compatibility view of overcurrent protection functions.

        New V2 code should prefer:

            elements_by_type("OVERCURRENT")

        This property does not represent authoritative storage.
        """

        return [
            element.protection_function
            for element in self.elements_by_type(
                "OVERCURRENT"
            )
        ]

    # -----------------------------------------------------------------

    @property
    def distance_relays(
        self,
    ) -> List[Any]:
        """
        Compatibility view of distance protection functions.

        New V2 code should prefer:

            elements_by_type("DISTANCE")

        This property does not represent authoritative storage.
        """

        return [
            element.protection_function
            for element in self.elements_by_type(
                "DISTANCE"
            )
        ]

    # =================================================================
    # STATUS
    # =================================================================

    def status(
        self,
    ) -> Dict[str, Any]:
        """
        Return structured ProtectionSystem status.

        The latest decisions are included as diagnostic data.
        """

        return {
            "element_count": len(
                self._elements
            ),
            "relay_count": len(
                self.relays()
            ),
            "decision_count": len(
                self._last_decisions
            ),
            "elements": [
                element.status()
                for element in self._execution_order()
            ],
            "last_decisions": [
                decision.as_dict()
                for decision in self._last_decisions
            ],
        }

    # =================================================================
    # REPRESENTATION
    # =================================================================

    def __repr__(
        self,
    ) -> str:
        """
        Return concise developer-facing representation.
        """

        return (
            f"<ProtectionSystem "
            f"elements={len(self._elements)}, "
            f"relays={len(self.relays())}, "
            f"decisions={len(self._last_decisions)}>"
        )


__all__ = [
    "ProtectionSystem",
]
