# ============================================================
# File: core/application/commands/__init__.py
# GridForge V2 — Headless Application Commands
# Author: Subhendu Mishra
# ============================================================

"""Public package API for immutable Application command contracts."""

from __future__ import annotations

# Bus has a dedicated canonical command module.
from .create_bus import CreateBusCommand

from .model_commands import (
    CREATE_BUS,
    DELETE_BUS,
    DeleteBusCommand,

    CREATE_LINE,
    DELETE_LINE,
    CreateLineCommand,
    DeleteLineCommand,

    CREATE_TRANSFORMER,
    DELETE_TRANSFORMER,
    CreateTransformerCommand,
    DeleteTransformerCommand,

    CREATE_LOAD,
    DELETE_LOAD,
    UPDATE_LOAD,
    CreateLoadCommand,
    DeleteLoadCommand,
    UpdateLoadCommand,

    CREATE_GRID,
    DELETE_GRID,
    UPDATE_GRID,
    CreateGridCommand,
    DeleteGridCommand,
    UpdateGridCommand,

    CREATE_BRANCH,
    UPDATE_BRANCH,
    DELETE_BRANCH,
    CreateBranchCommand,
    UpdateBranchCommand,
    DeleteBranchCommand,

    CREATE_CABLE,
    UPDATE_CABLE,
    DELETE_CABLE,
    CreateCableCommand,
    UpdateCableCommand,
    DeleteCableCommand,

    CREATE_SWITCH,
    UPDATE_SWITCH,
    DELETE_SWITCH,
    OPEN_SWITCH,
    CLOSE_SWITCH,
    PUT_SWITCH_IN_SERVICE,
    TAKE_SWITCH_OUT_OF_SERVICE,
    CreateSwitchCommand,
    UpdateSwitchCommand,
    DeleteSwitchCommand,
    OpenSwitchCommand,
    CloseSwitchCommand,
    PutSwitchInServiceCommand,
    TakeSwitchOutOfServiceCommand,

    CREATE_DISCONNECTOR,
    UPDATE_DISCONNECTOR,
    DELETE_DISCONNECTOR,
    OPEN_DISCONNECTOR,
    CLOSE_DISCONNECTOR,
    PUT_DISCONNECTOR_IN_SERVICE,
    TAKE_DISCONNECTOR_OUT_OF_SERVICE,
    CreateDisconnectorCommand,
    UpdateDisconnectorCommand,
    DeleteDisconnectorCommand,
    OpenDisconnectorCommand,
    CloseDisconnectorCommand,
    PutDisconnectorInServiceCommand,
    TakeDisconnectorOutOfServiceCommand,

    CREATE_FUSE,
    UPDATE_FUSE,
    DELETE_FUSE,
    BLOW_FUSE,
    RESET_FUSE,
    PUT_FUSE_IN_SERVICE,
    TAKE_FUSE_OUT_OF_SERVICE,
    CreateFuseCommand,
    UpdateFuseCommand,
    DeleteFuseCommand,
    BlowFuseCommand,
    ResetFuseCommand,
    PutFuseInServiceCommand,
    TakeFuseOutOfServiceCommand,
)


__all__ = [
    "CREATE_BUS",
    "DELETE_BUS",
    "CreateBusCommand",
    "DeleteBusCommand",

    "CREATE_LINE",
    "DELETE_LINE",
    "CreateLineCommand",
    "DeleteLineCommand",

    "CREATE_TRANSFORMER",
    "DELETE_TRANSFORMER",
    "CreateTransformerCommand",
    "DeleteTransformerCommand",

    "CREATE_LOAD",
    "DELETE_LOAD",
    "UPDATE_LOAD",
    "CreateLoadCommand",
    "DeleteLoadCommand",
    "UpdateLoadCommand",

    "CREATE_GRID",
    "DELETE_GRID",
    "UPDATE_GRID",
    "CreateGridCommand",
    "DeleteGridCommand",
    "UpdateGridCommand",

    "CREATE_BRANCH",
    "UPDATE_BRANCH",
    "DELETE_BRANCH",
    "CreateBranchCommand",
    "UpdateBranchCommand",
    "DeleteBranchCommand",

    "CREATE_CABLE",
    "UPDATE_CABLE",
    "DELETE_CABLE",
    "CreateCableCommand",
    "UpdateCableCommand",
    "DeleteCableCommand",

    "CREATE_SWITCH",
    "UPDATE_SWITCH",
    "DELETE_SWITCH",
    "OPEN_SWITCH",
    "CLOSE_SWITCH",
    "PUT_SWITCH_IN_SERVICE",
    "TAKE_SWITCH_OUT_OF_SERVICE",
    "CreateSwitchCommand",
    "UpdateSwitchCommand",
    "DeleteSwitchCommand",
    "OpenSwitchCommand",
    "CloseSwitchCommand",
    "PutSwitchInServiceCommand",
    "TakeSwitchOutOfServiceCommand",

    "CREATE_DISCONNECTOR",
    "UPDATE_DISCONNECTOR",
    "DELETE_DISCONNECTOR",
    "OPEN_DISCONNECTOR",
    "CLOSE_DISCONNECTOR",
    "PUT_DISCONNECTOR_IN_SERVICE",
    "TAKE_DISCONNECTOR_OUT_OF_SERVICE",
    "CreateDisconnectorCommand",
    "UpdateDisconnectorCommand",
    "DeleteDisconnectorCommand",
    "OpenDisconnectorCommand",
    "CloseDisconnectorCommand",
    "PutDisconnectorInServiceCommand",
    "TakeDisconnectorOutOfServiceCommand",

    "CREATE_FUSE",
    "UPDATE_FUSE",
    "DELETE_FUSE",
    "BLOW_FUSE",
    "RESET_FUSE",
    "PUT_FUSE_IN_SERVICE",
    "TAKE_FUSE_OUT_OF_SERVICE",
    "CreateFuseCommand",
    "UpdateFuseCommand",
    "DeleteFuseCommand",
    "BlowFuseCommand",
    "ResetFuseCommand",
    "PutFuseInServiceCommand",
    "TakeFuseOutOfServiceCommand",
]
